## see https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/-/blob/master/.gitlab-ci.yml

image: julia:1.7        # image comes from Docker hub

before_script:
    - apt-get -qq update; apt-get -y install git rsync
    - julia --project=@. -e "import Pkg; Pkg.build()"

default:
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = false)"
    # - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    # - julia --project=test/coverage test/coverage/coverage-summary.jl


pages:
  stage: deploy
  script:
    - export # show all GitLab variables
    - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    # - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))' # no instantiate...
    - julia --project=docs --color=yes docs/make.jl
    - echo $(ls ./)
    #- echo $(ls ../)
    - echo $(pwd)
    #- git branch -a
    - git checkout -b gl-pages origin/gl-pages # Git shallow clone = 0 to get all branches
    - echo $(ls ./)
    #- rm -r public/*
    - rsync -r --exclude=".git" --exclude=".gitignore" ./* public/
    # - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master
    - tags 
    #refs:
    #  - master
    #  - tags
    #variables:
    #  - $CI_COMMIT_BRANCH == "main"

