## see https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/-/blob/master/.gitlab-ci.yml

image: julia:1.7        # image comes from Docker hub

before_script:
    - apt-get -qq update; apt-get -y install git rsync
    - julia --project=@. -e "import Pkg; Pkg.build()"

default:
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = false)"
    # - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    # - julia --project=test/coverage test/coverage/coverage-summary.jl


pages:
  stage: deploy
  script:
    ## - export # show all GitLab variables
    - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    # - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))' # no instantiate...
    - julia --project=docs --color=yes docs/make.jl
    - echo $(ls ./)
    #- echo $(ls ../)
    - echo $(pwd)
    #- git branch -a
    - mkdir tmppub
    - mv .git tmppub/
    - cd tmppub
    - echo $(ls ./) 
    - git checkout -b gl-pages origin/gl-pages 
    - echo $(ls ./)
    - rsync -a --exclude=".git" --exclude=".gitignore" ../tmppub/*  ../public/
    # - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    refs:
      - main
      - tags
  
  #only:
  #  - main
  #  - tags 
  
  #only:
    #refs:
    #  - main
    #  - tags
    #variables:
    #  - $CI_COMMIT_BRANCH == "main"

