name = "EikonalSolvers"
uuid = "0631ba50-6b23-11e9-3fc3-378508ba069a"
authors = ["Andrea Zunino <inverseproblem@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = ">=1.0"
