name = "EikonalSolvers"
uuid = "0631ba50-6b23-11e9-3fc3-378508ba069a"
authors = ["Andrea Zunino <inverseproblem@users.noreply.github.com>"]
version = "0.4.3"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
